################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2021-2022, The Raetro authors and contributors
################################################################################
name: Test Build (Single SDRAM for sockit)
################################################################################
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  TARGET: TurboGrafx16
    ###############################################################################
jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:17.0
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2 - RTL synthesis Single SDRAM
      - name: Run compilation flow for Single SDRAM
        run: quartus_sh --flow compile ${{ env.TARGET }}.qpf
      # 3 - Get current version for tagging binary
      - name: Get the version
        id: version
        run: echo "::set-output name=version::$(date +'%Y%m%d')"
      # 4 - Copy Artifacts
      - name: Create a copy and tag with version
        run: |
          mkdir -p release
          cp output_files/${{ env.TARGET }}.rbf release/${{ env.TARGET }}_${{ steps.version.outputs.version }}.rbf
          cp output_files/${{ env.TARGET }}.fit.summary release/${{ env.TARGET }}.fit_${{ steps.version.outputs.version }}.txt
      # 5 - Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}_${{ steps.version.outputs.version }}
          path: release/
